evenement_homepage:
    path:     /evenements
    defaults: { _controller: EvenementBundle:Default:index }
evenement_ajout:
    path:     /AjoutEvenement
    defaults: { _controller: EvenementBundle:Evenement:ajout }
evenement_list:
    path:     /listesEvenements
    defaults: { _controller: EvenementBundle:Evenement:list }
Evenement_modifier:
    path:     /ModifierEvenement
    defaults: { _controller: EvenementBundle:Evenement:Update }
Evenement_supprimer:
    path:     /SupprimerEvenement
    defaults: { _controller: EvenementBundle:Evenement:Delete }
evenement_parent:
    path:     /evenementParent
    defaults: { _controller: EvenementBundle:Evenement:listFront }
evenement_listemobile:
    path:     /evenement/liste
    defaults: { _controller: EvenementBundle:Evenement:liste }

evenement_search:
    path:     /evenement/search/{key}
    defaults: { _controller: EvenementBundle:Evenement:search }

evenement_addM:
    path:     /evenement/ajout
    defaults: { _controller: EvenementBundle:Evenement:addM}