activite_homepage:
    path:     /homepage
    defaults: { _controller: ActiviteBundle:Default:index }

activite_viewActivite:
    path:     /activite/view
    defaults: { _controller: ActiviteBundle:Activite:afficheBack }

activite_list:
    path:     /activite/list
    defaults: { _controller: ActiviteBundle:Activite:list }


activite_search:
    path:     /activite/search/{key}
    defaults: { _controller: ActiviteBundle:Activite:listAll}


activite_liste:
    path:     /activite/liste
    defaults: { _controller: ActiviteBundle:Activite:listFront }

activite_essay:
    path:     /activite/ajout
    defaults: { _controller: ActiviteBundle:Activite:newAct }

activite_createActivite:
    path:     /activite/create
    defaults: { _controller: ActiviteBundle:Activite:createActivite }


activite_afficherActivite:
    path:     /activite/afficher
    defaults: { _controller: ActiviteBundle:Activite:afficheBack }


activite_modifBackEnseignant:
    path:     /ModificationActivite/{id}
    defaults: { _controller: ActiviteBundle:Activite:updateActivite  }

activite_updateActivite:
    path:     /activite/update/{id}
    defaults: { _controller: ActiviteBundle:Activite:updateActivite }


activite_deleteActivite:
    path:     /activite/delete/{id}
    defaults: { _controller: ActiviteBundle:Activite:deleteActivite }


activite_afficherFrontctivite:
    path:     /activite/affich
    defaults: { _controller: ActiviteBundle:Activite:viewActivite }


activite_show:
    path:     /activite/show/{id}
    defaults: { _controller: ActiviteBundle:Activite:showActivite }

activite_shw:
    path:     /activite/showi/{id}
    defaults: { _controller: ActiviteBundle:Activite:DetailsActivite }







