<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEvenement($key)
    {
        $query=$this->getEntityManager()
            ->createQuery(" Select  u from EvenementBundle:Evenement u where u.intitule LIKE :intitule ")
            ->setParameter('intitule','%'.$key.'%');

        return $query->getResult();
    }
}
