<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{
    public function MyCars($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT v FROM ApiBundle:Car v WHERE v.proprio=:i ")

            ->setParameter('i', $id);

        return $result = $query->getResult();
    }

    public function AllCars()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT v.matricule,v.marque,v.modele,v.couleur,v.nbSieges FROM ApiBundle:Car v  ");


        return $result = $query->getResult();
    }
}
