recette_homepage:
    path:     /es
    defaults: { _controller: RecetteBundle:Default:index }
listAjax:
      path:     /listAjax
      defaults: { _controller: RecetteBundle:Default:AllRecetteJson }